service: video-transcoding

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverlessUser
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*Bucket
        - s3:*Object
      Resource:
        - "arn:aws:s3:::${file(config.json):S3_BUCKET}/*"
        - "arn:aws:s3:::${file(config.json):S3_BUCKET_DESTINATION}/*"

constructs:
  jobs:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: src/functions/worker.handler
      memorySize: 1024
      timeout: 900
      environment:
        S3_BUCKET_DESTINATION: ${file(config.json):S3_BUCKET_DESTINATION}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-lift

functions:
  publisher:
    handler: src/functions/publisher.handler
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
    events:
      - s3:
          bucket: ${file(config.json):S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mkv
