service: video-transcoding

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverlessUser
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}

constructs:
  jobs:
    type: queue
    worker:
      handler: src/functions/worker.handler

functions:
  publisher:
    handler: src/functions/publisher.handler
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
      AWS_REGION: ${provider:region}
    events:
      - s3:
          bucket: ${file(config.json):S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-lift
