name: Deploy Serverless Functions
on:
  push:
    branch: [master]
jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Serverless globally 🌍
        run: npm install -g serverless
      - name: Setup Serverless credentials 🔒
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile serverlessUser
      - name: Install dependencies 🔧
        run: yarn
      - name: Deploy functions to AWS 📦
        run: yarn deploy
